### ISSUE TITLE
Failed to post request on RPC :  {Caused by: java.io.EOFException: \n not found:…}  	

### ISSUE THREAD

**Issue by huananshi** [nervosnetwork/ckb-sdk-java#240]
at org.nervos.ckb.service.RpcService.post(RpcService.java:41)
	at org.nervos.ckb.service.Api.getBlockchainInfo(Api.java:113)
	at org.nervos.ckb.RpcExample.getBlockchainInfo(RpcExample.java:49)
	at org.nervos.ckb.RpcExample.run(RpcExample.java:24)
	at org.nervos.ckb.RpcExample.main(RpcExample.java:30)
Caused by: java.io.EOFException: \n not found: limit=210 content=000000cece000000180000002c0000005900000068000000bd00000010000000…

**Comment by duanyytop** [comment]
Which rpc you call? The error information is from ckb, so what is your problem ?

**Comment by quake** [comment]
it looks like your ckb rpc endpoint is not correct, could you check it by curl?
```
echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "get_tip_block_number",
    "params": []
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
http://localhost:8114
```
